### ISSUE TITLE
Program prerequisites for usage

### ISSUE THREAD

**Issue by souravs89** [wbg-bigdata/nightlights-api#11]
Hi, I want to use the nighttime lights data for my research and this dataset seems to suit my work. However, I hardly have any background in computer programming. Is there any programming prerequisite for this or following the API is easy enough.

**Comment by dereklieu** [comment]
@souravs89 depending on how much of the data you need to access, you may need some level of programming experience. If you only need access to a few slices here and there, you can access it directly using your browser. For example, try opening [the first link in the documentation](http://api.nightlights.io/):

> [http://api.nightlights.io/months/1993.3-1993.4/districts/gujarat-anand](http://api.nightlights.io/months/1993.3-1993.4/districts/gujarat-anand)

Working with the API programmatically will always be a better experience though, since that is what it's built for. There is a lot of free material online for accessing and manipulating data with tools like Python, I would recommend looking those up.

**Comment by souravs89** [comment]
Thank you very much Derek!
